# syntax=docker/dockerfile:1

# Multi-stage production build for the Mindful Healing Trips Next.js app.
# Optimized for a small, non-root runtime image via Next.js "standalone" output.

FROM node:22-alpine AS base
# Required by Prisma's query engine and a few native deps on Alpine.
RUN apk add --no-cache libc6-compat
WORKDIR /app
RUN corepack enable

# --- deps: install dependencies with a frozen lockfile -----------------------
FROM base AS deps
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY prisma ./prisma
# `pnpm install`'s postinstall (`prisma generate`) only needs the schema --
# it never opens a database connection -- but `prisma.config.ts`'s
# `env("DATABASE_URL")` resolves the variable *eagerly* for every Prisma
# CLI command, `generate` included, and throws if it's simply unset
# ("Cannot resolve environment variable: DATABASE_URL"), regardless of
# whether it points anywhere reachable. Every other environment already
# guarantees DATABASE_URL is at least *present* before `pnpm install` runs
# (task setup's .env.local, ci.yml's job env, Vercel's dashboard env) --
# this placeholder does the same for the one environment that didn't
# (this stage). It is never used to connect to anything and is not a
# secret: don't replace it with a real DATABASE_URL build-arg.
ENV DATABASE_URL="postgresql://build:build@localhost:5432/build?schema=public"
RUN pnpm install --frozen-lockfile

# --- builder: compile the Next.js app ----------------------------------------
FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
# The Prisma client generated by `deps`' `pnpm install` (postinstall ->
# `prisma generate`, output = src/generated/prisma per prisma/schema.prisma)
# lives outside node_modules and is gitignored, so `COPY . .` below can't
# bring it in from the build context -- it must be copied explicitly from
# the `deps` layer, or `pnpm build` fails with "Can't resolve
# '@/generated/prisma/client'".
COPY --from=deps /app/src/generated ./src/generated
COPY . .
# NEXT_PUBLIC_* values are baked into the client bundle at build time --
# this is public, non-secret build-time config, unlike DATABASE_URL below.
ARG NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
# Every DB-backed route (/, /voyages, /voyages/[slug], /destinations,
# /destinations/[slug], /contact, /sitemap.xml) declares
# `export const dynamic = "force-dynamic"` (or, for the two `[slug]`
# routes, is already rendered on demand because there's no
# `generateStaticParams`) -- so `next build` never queries PostgreSQL.
# DATABASE_URL is therefore intentionally *not* set here: it is runtime
# configuration, injected only in Kubernetes via a Secret (see
# src/lib/db/prisma.ts and docs/ARCHITECTURE.md). Previously this stage
# took DATABASE_URL as a build ARG pointed at a real, reachable Postgres
# so the static prerender above could succeed, baking whatever rows
# existed in it into this image's static output -- see
# docs/adr/0009-image-build-time-data-baking.md in the infrastructure
# repository, now superseded by making those routes dynamic instead.
RUN pnpm build

# --- runner: minimal production runtime --------------------------------------
FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs

# `pnpm build`'s postbuild script already copies public/ and .next/static
# into .next/standalone (scripts/copy-standalone-assets.mjs), so this one
# copy is a fully self-contained runtime.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

USER nextjs
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

CMD ["node", "server.js"]
